### model
model_name_or_path: /scratch/project_2015499/AC_project/models/Qwen2.5-0.5B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.05

### dataset
dataset: emotion_train
eval_dataset: emotion_validation
template: qwen
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: /scratch/project_2015499/AC_project/qwen25_emotion_lora
logging_steps: 20
save_steps: 100  
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard
logging_dir: /scratch/project_2015499/AC_project/qwen25_emotion_logs

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
learning_rate: 2e-5
num_train_epochs: 2  
lr_scheduler_type: cosine
warmup_ratio: 0.1
weight_decay: 0.01
max_grad_norm: 1.0
bf16: false
fp16: true
ddp_timeout: 180000000
optim: adamw_torch
seed: 42  

### eval
do_eval: true
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 100  
metric_for_best_model: eval_loss
greater_is_better: false
load_best_model_at_end: true
save_total_limit: 2